server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/byron_home?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# 微信小程序配置
wx:
  miniapp:
    appid: wx707fddd03d3dd679
    secret: 977b001b48397f4f5bab95fc9568878a

# knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN